/**
 * Enough spherical astronomy to point a camera at the real sky.
 *
 * Everything here is standard textbook transformation, not approximation for
 * looks: given a star's right ascension and declination, an observer's latitude
 * and longitude, and a moment in time, it returns where that star actually is
 * in the sky, and then where that lands on screen for a viewer facing a given
 * compass direction. That is what makes "facing north over Nittambuwa at 9pm"
 * a true statement rather than a caption on a decorative pattern.
 *
 * Coordinates come from src/lib/sky-data.json, generated by
 * scripts/build-sky-data.mjs. Right ascension there is in DEGREES in the
 * -180..180 convention (verified by the generator, which throws if the upstream
 * convention ever changes).
 */

const DEG = Math.PI / 180;

/** Nittambuwa, Sri Lanka, where CeyagMark actually is. */
export const OBSERVER = { latitude: 7.14, longitude: 80.1 };

/**
 * Greenwich Mean Sidereal Time in degrees. Accurate to well under a second of
 * arc across decades, which is orders of magnitude more than a background
 * needs, but it costs nothing to use the real expression.
 */
function gmstDegrees(date: Date): number {
  const jd = date.getTime() / 86400000 + 2440587.5;
  const d = jd - 2451545.0;
  return 280.46061837 + 360.98564736629 * d;
}

/** Local sidereal time in degrees, normalised to 0..360. */
export function localSiderealDegrees(date: Date, longitudeEast: number): number {
  return ((gmstDegrees(date) + longitudeEast) % 360 + 360) % 360;
}

export type Horizontal = {
  /** Degrees above the horizon. Negative means below it, i.e. not visible. */
  altitude: number;
  /** Degrees clockwise from north. */
  azimuth: number;
};

/** Equatorial (RA/Dec, degrees) to horizontal (alt/az) for an observer and time. */
export function toHorizontal(
  raDeg: number,
  decDeg: number,
  latitudeDeg: number,
  lstDeg: number,
): Horizontal {
  const H = (lstDeg - raDeg) * DEG;
  const dec = decDeg * DEG;
  const lat = latitudeDeg * DEG;

  const sinAlt = Math.sin(dec) * Math.sin(lat) + Math.cos(dec) * Math.cos(lat) * Math.cos(H);
  const altitude = Math.asin(Math.max(-1, Math.min(1, sinAlt)));

  const azimuth = Math.atan2(
    -Math.cos(dec) * Math.sin(H),
    Math.sin(dec) * Math.cos(lat) - Math.cos(dec) * Math.sin(lat) * Math.cos(H),
  );

  return {
    altitude: altitude / DEG,
    azimuth: ((azimuth / DEG) % 360 + 360) % 360,
  };
}

export type Camera = {
  /** Compass direction the viewer faces, degrees clockwise from north. */
  facing: number;
  /** How far up the camera is tilted, degrees. */
  tilt: number;
  /** Horizontal field of view, degrees. */
  fov: number;
  width: number;
  height: number;
  /**
   * Stars below this altitude are culled. Defaults to the horizon, because a
   * real view of the sky does not include the half of it that is under the
   * ground. Made part of the camera rather than left to each caller: a
   * forgotten horizon check renders a physically wrong sky that still looks
   * plausible, which is the worst kind of bug to find later.
   */
  minAltitude?: number;
};

export type Projected = { x: number; y: number; altitude: number };

/**
 * Gnomonic projection of a horizontal coordinate onto the screen.
 *
 * Returns null when the point is behind the camera or too near the edge of the
 * projection, where a gnomonic mapping stretches toward infinity. A linear
 * alt/az-to-pixels mapping would have been fewer lines but visibly bends the
 * constellations at the wide field this uses, which defeats the point of having
 * real geometry in the first place.
 */
export function project(h: Horizontal, cam: Camera): Projected | null {
  const alt = h.altitude * DEG;
  const az = h.azimuth * DEG;
  const f0 = cam.facing * DEG;
  const t0 = cam.tilt * DEG;

  // Observer-frame unit vector: (north, east, up).
  const n = Math.cos(alt) * Math.cos(az);
  const e = Math.cos(alt) * Math.sin(az);
  const u = Math.sin(alt);

  // Camera basis. `right` is horizontal, east of the facing direction; `up` is
  // perpendicular to both and reduces to the zenith when tilt is zero.
  const fwd = [Math.cos(t0) * Math.cos(f0), Math.cos(t0) * Math.sin(f0), Math.sin(t0)];
  const right = [-Math.sin(f0), Math.cos(f0), 0];
  const up = [-Math.sin(t0) * Math.cos(f0), -Math.sin(t0) * Math.sin(f0), Math.cos(t0)];

  if (h.altitude < (cam.minAltitude ?? 0)) return null;

  const z = n * fwd[0]! + e * fwd[1]! + u * fwd[2]!;
  if (z <= 0.2) return null;

  const x = n * right[0]! + e * right[1]! + u * right[2]!;
  const y = n * up[0]! + e * up[1]! + u * up[2]!;

  const focal = cam.width / 2 / Math.tan((cam.fov * DEG) / 2);
  return {
    x: cam.width / 2 + (x / z) * focal,
    y: cam.height / 2 - (y / z) * focal,
    altitude: h.altitude,
  };
}

/**
 * The moment a given scroll position represents: dusk to dawn, 18:00 through
 * 06:00 the next morning, on today's date. Today's date is deliberate, it
 * means the sky overhead is the sky actually overhead, and it drifts through
 * the year the way the real one does.
 */
export function timeForScroll(progress: number, now = new Date()): Date {
  const p = Math.max(0, Math.min(1, progress));
  const d = new Date(now);
  d.setHours(18, 0, 0, 0);
  return new Date(d.getTime() + p * 12 * 3600 * 1000);
}

/** Compass facing per route, so each page opens on a different quarter of the sky. */
const FACING_BY_PATH: Record<string, number> = {
  "/": 0,
  "/services": 90,
  "/consulting": 135,
  "/approach": 180,
  "/portfolio": 225,
  "/about": 270,
  "/contact": 315,
  "/growth-audit": 45,
  "/free-audit": 60,
  "/built-by": 200,
  "/book": 300,
  "/quiz": 20,
};

/**
 * Facing for a path. Unlisted routes (the four case studies, legal pages) get a
 * stable direction derived from the path itself rather than defaulting every
 * one of them to north, so sibling pages still differ.
 */
export function facingForPath(path: string): number {
  const known = FACING_BY_PATH[path];
  if (known !== undefined) return known;
  let hash = 0;
  for (let i = 0; i < path.length; i++) hash = (hash * 31 + path.charCodeAt(i)) >>> 0;
  return hash % 360;
}
